# Generated by Django 4.0.3 on 2022-04-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_shoppingcart_unique_name_user_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='favorite',
            name='unique_name_favorites',
        ),
        migrations.RemoveConstraint(
            model_name='shoppingcart',
            name='unique_name_user',
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_name_recipe_in_favorites'),
        ),
        migrations.AddConstraint(
            model_name='shoppingcart',
            constraint=models.UniqueConstraint(fields=('user', 'recipe'), name='unique_name_recipe_in_shopping_cart'),
        ),
    ]
